version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8080:8080
    image: app:instruments_django
    container_name: instruments_django_container
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
