version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=instruments_db
      - MYSQL_USER=instruments_admin
      - MYSQL_PASSWORD=instruments
      - MYSQL_ROOT_PASSWORD=null
    volumes:
      - .instruments_db_data:/var/lib/mysql
    ports:
      - "33066:3306"
